2019-12-10T15:55:36|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\Matteo\eclipse-workspace\scopefoundry\Microscopes\VirtualMicroscopeJoyStick\JoystickApp.py", line 44, in <module>
    app = FancyMicroscopeApp(sys.argv)
  File "C:\Users\Matteo\eclipse-workspace\scopefoundry\ScopeFoundry\base_app.py", line 338, in __init__
    self.setup()
  File "C:\Users\Matteo\eclipse-workspace\scopefoundry\Microscopes\VirtualMicroscopeJoyStick\JoystickApp.py", line 21, in setup
    self.add_hardware(VirtualFunctionGenHW(self))
  File "C:\Users\Matteo\eclipse-workspace\scopefoundry\ScopeFoundry\hardware.py", line 81, in __init__
    self.setup()
  File "C:\Users\Matteo\eclipse-workspace\scopefoundry\ScopeFoundryHW\virtual_function_gen\vfunc_gen_hw.py", line 14, in setup
    self.settings.New(name='amplitude', initial=1.0, dtype=float, ro=False, decimal=4)
  File "C:\Users\Matteo\eclipse-workspace\scopefoundry\ScopeFoundry\logged_quantity.py", line 1231, in New
    lq = LoggedQuantity(name=name, dtype=dtype, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'decimal'

