2019-12-18T18:48:27|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\logged_quantity.py", line 241, in update_value
    self.hardware_set_func(self.val)
  File "C:\LabPrograms\Python\FluigentHardwareUpdated\PumpDevice.py", line 111, in save_p
    self.pressure.append(pressure_read.value)
AttributeError: 'MFCSDevice' object has no attribute 'pressure'

