2019-12-18T19:02:50|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\FluigentHardwareUpdated\PumpHardware.py", line 53, in connect
    self.set_save_pressure.hardware_set_func = self.MFCS.set_save_p
AttributeError: 'MFCSHardware' object has no attribute 'set_save_pressure'

2019-12-18T19:02:52|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\FluigentHardwareUpdated\PumpHardware.py", line 53, in connect
    self.set_save_pressure.hardware_set_func = self.MFCS.set_save_p
AttributeError: 'MFCSHardware' object has no attribute 'set_save_pressure'

